CREATE TABLE ORC_PROCESS (
    UUID VARCHAR(255) PRIMARY KEY,
    TENANT_ID VARCHAR(255) NOT NULL,
    ENTE VARCHAR(255) NOT NULL ,
    START_USER VARCHAR(255) NOT NULL ,
    AREA VARCHAR(255) NOT NULL ,
    PROCEDURA VARCHAR(255) NOT NULL,
    SSM_MACHINE_ID VARCHAR(255) NOT NULL,
    DOMAIN_ORCH_ENDPOINT VARCHAR(255) NOT NULL,
    SSM_STATE VARCHAR(255) NOT NULL,
    START_TIME TIMESTAMP NOT NULL ,
    END_TIME TIMESTAMP ,
    PROCESS_TYPE VARCHAR(50) NOT NULL CHECK (PROCESS_TYPE IN ('PSEUDO_SYNCH', 'BATCH', 'CRON', 'AGGREGATOR')),
    BUSINESS_STATE VARCHAR(50) NOT NULL CHECK (BUSINESS_STATE IN ('RUNNING', 'COMPLETED', 'FAILED', 'PARTIALLY_FAILED')),
    PARENT_UUID VARCHAR(255) ,
    CONTEXT TEXT ,
    PROCESS_RESULT TEXT
);
CREATE TABLE ORC_PROCESS_HISTORY (
    ID INT AUTO_INCREMENT PRIMARY KEY ,
    PROCESS_UUID VARCHAR(255) NOT NULL ,
    EVENT_TIME TIMESTAMP NOT NULL ,
    BS_SOURCE_STATE VARCHAR(255) NOT NULL ,
    BS_TARGET_STATE VARCHAR(255) NOT NULL ,
    SM_SOURCE_STATE VARCHAR(255) NOT NULL,
    SM_TARGET_STATE VARCHAR(255) NOT NULL ,
    FOREIGN KEY (PROCESS_UUID) REFERENCES ORC_PROCESS(UUID)
);
