apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: orchestraton-ingress
  namespace: jentetest
spec:
  ingressClassName: nginx
  rules:
    - host: active-mq.minikube
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jente-activemq
                port:
                  number: 8161
    - host: lra-coordinator.minikube
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: lra-coordinator
                port:
                  number: 8080
    - host: saga.minikube
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: camel-orchestration
                port:
                  number: 80                  
    - host: saga-ssm.minikube
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: spring-state-machine-orchestration
                port:
                  number: 80 
    - host: saga-ssm-factory.minikube
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ssma-orchestration-factory
                port:
                  number: 80                                    
    - host: prometheus.minikube
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prometheus
                port:
                  number: 9090                  
    - host: grafana.minikube
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: grafana
                port:
                  number: 3000                                    
    - host: rabbitmq.minikube
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rabbitmq
                port:
                  number: 80                                    
    - host: orch-manager.minikube
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: orch-manager-service
                port:
                  number: 8080                                                      