package exception.data;



import exception.data.JEnteErrorDetail;

import java.net.URI;
import java.util.List;

public class JEnteProblemDetail {
    /**
     * A URI reference that identifies the problem type.
     * This URI should provide human-readable documentation for the problem when dereferenced.
     */
    private URI type;
    /**
     * A short, human-readable summary of the problem type.
     * It should remain consistent for the same type of problem.
     */
    private String title;
    /**
     * The HTTP status code generated by the server for this occurrence of the problem.
     */
    private int status;
    /**
     * A human-readable explanation specific to this occurrence of the problem.
     */
    private String detail;
    /**
     * A URI reference that identifies the specific occurrence of the problem. It may or may not yield further information if dereferenced.
     */
    private URI instance;
    /**
     * A unique identifier for tracing the request through the system assigned by the observer api
     */
    private String traceId;
    /**
     * An identifier used to identify the span where the problem has occured... obtained by
     * the observer api
     */
    private String spanId;
    /**
     * The code of the application error; all the errors will be censited for each "Area/Procedura"
     * and these code and description will be managed by the team responsible for "the Area/Procedura"
     */
    private String errorCode;
    /**
     * A list of objects, where each object contains two attributes 'key' and 'value', providing additional context-specific information.
     */
    private List<JEnteErrorDetail> details;

    public JEnteProblemDetail() {
    }

    public JEnteProblemDetail(URI type, String title, int status, String detail, URI instance, String traceId, String spanId, String errorCode, List<JEnteErrorDetail> details) {
        this.type = type;
        this.title = title;
        this.status = status;
        this.detail = detail;
        this.instance = instance;
        this.traceId = traceId;
        this.spanId = spanId;
        this.errorCode = errorCode;
        this.details = details;
    }

    public URI getType() {
        return type;
    }

    public String getTitle() {
        return title;
    }

    public int getStatus() {
        return status;
    }

    public String getDetail() {
        return detail;
    }

    public URI getInstance() {
        return instance;
    }

    public String getTraceId() {
        return traceId;
    }

    public String getSpanIdd() {
        return spanId;
    }

    public String getErrorCode() {
        return errorCode;
    }

    public List<JEnteErrorDetail> getDetails() {
        return details;
    }

    @Override
    public String toString() {
        return "JEnteProblemDetail{" +
                "type=" + type +
                ", title='" + title + '\'' +
                ", status=" + status +
                ", detail='" + detail + '\'' +
                ", instance=" + instance +
                ", traceId='" + traceId + '\'' +
                ", spanId='" + spanId + '\'' +
                ", errorCode='" + errorCode + '\'' +
                ", details=" + details +
                '}';
    }
}
