spring:
  application:
    name: protocollo
springdoc:
  swagger-ui:
    enabled: true
    path: /v1/protocollo/swagger-ui.html
  api-docs:
    path: /v1/protocollo-docs
server:
  port: 8280
management:
  endpoints:
    web:
      exposure:
        include: "*"
  server:
    port: 9180
