/**
 * Copyright 2020 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
 /**
 *
 * Questa e' la unit rule che viene invocata prima della
 * creazione della pratica e serve a verificare se devono
 * essere fatte delle azioni (i.e. rimossi interventi e/o dichiarazioni)
 * in base alla scelta delle discriminanti
 *
 */
package org.gds.misc.drools.units;
unit InformazioniPreliminariUnit;

import org.gds.misc.drools.model.fact.Procedimento;
import org.gds.misc.drools.model.fact.Attivita;
import org.gds.misc.drools.model.fact.MacroAttivita;
import org.gds.misc.drools.model.preliminare.DichirazioneDaRimuovere;
import org.gds.misc.drools.model.preliminare.InterventoDaRimuovere
import org.gds.misc.drools.org.gds.misc.drools.support.XPathHelper;

rule SmallDepodsitApprove when
//    $p: /procedimento[ tipoPratica.attivita.macroAttivita.codice == 'CAP' ]
//    $p: /procedimento[ xml == 'xxxX']
//    $p: /tipoPratica[ attivita.macroAttivita.codice == 'CAP' ]
//      $p: eval(leggi('Ciao'))
//      and
//      eval ($p == 'Ciao')
       $t: /tipoPratica[ attivita.macroAttivita.codice == 'CAP' ]
       and
       $xmlDocument: /xmlDocument
//       and
//       eval(XPathHelper.verifica($xml,'CIAO'));
//       eval(XPathHelper.
//						ottieniValoreDaCampoInDichiarazione($xmlDocument,'intDatiCatastali','dichDatiCatastali', 'CATFOGLIO')!=null)
//						ottieniValoreDaCampoInDichiarazione($xmlDocument,null,null, 'CATFOGLIO')!=null)
then
    elementiDaRimuovere.append(new InterventoDaRimuovere("codiceIntervento")) ;
end

query InformazioniPreliminari
    daRimuovere: /elementiDaRimuovere
end
