/**
 * Copyright 2020 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.gds.misc.drools.units;
unit ValidazioneUnit;

import org.gds.misc.drools.model.Procedimento;
import org.gds.misc.drools.model.Attivita;
import org.gds.misc.drools.model.MacroAttivita;
import org.gds.misc.drools.model.Errore;
import org.gds.misc.drools.model.Livello;
import org.gds.misc.drools.org.gds.misc.drools.support.XPathHelper;

rule SmallDepositApprove when
//    $p: /procedimento[ tipoPratica.attivita.macroAttivita.codice == 'CAP' ]
//    $p: /procedimento[ xml == 'xxxX']
//    $p: /tipoPratica[ attivita.macroAttivita.codice == 'CAP' ]
//      $p: eval(leggi('Ciao'))
//      and
//      eval ($p == 'Ciao')
       $t: /tipoPratica[ attivita.macroAttivita.codice == 'CAP' ]
       and
       $xml: /xml
       and
       eval(XPathHelper.verifica($xml,'CIAO'));
then
    errori.add(new Errore(Livello.DICHIRAZIONE,"descrizione","codiceIntervento","codiceDichiarazione",null) );
end

query Validazioni
    $e: /errori
end
