<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>org.gds.poc.orch</groupId>
	<artifactId>orch-manager-service</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>orch-manager-service</name>
	<description>Orchestator Manager Service</description>
	<properties>
		<spring-boot-version>3.3.2</spring-boot-version>
		<camel-version>4.4.0</camel-version>
		<java.version>21</java.version>
		<maven.compiler.source>21</maven.compiler.source>
		<maven.compiler.target>21</maven.compiler.target>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
	</properties>
	<dependencyManagement>
		<dependencies>
			<!-- Camel BOM -->
			<dependency>
				<groupId>org.apache.camel.springboot</groupId>
				<artifactId>camel-spring-boot-bom</artifactId>
				<version>${camel-version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
			<!-- Spring Boot BOM -->
			<dependency>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-dependencies</artifactId>
				<version>${spring-boot-version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>
	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-validation</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springdoc</groupId>
			<artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
			<version>2.6.0</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-jpa</artifactId>
		</dependency>
		<!-- RabbitMQ & Camel-->
		<dependency>
			<groupId>org.apache.camel.springboot</groupId>
			<artifactId>camel-core-starter</artifactId>
		</dependency>
		<dependency>
			<groupId>org.apache.camel.springboot</groupId>
			<artifactId>camel-bean-starter</artifactId>
		</dependency>
		<!-- use spring rabbitmq -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-amqp</artifactId>
		</dependency>
		<dependency>
			<groupId>org.apache.camel.springboot</groupId>
			<artifactId>camel-spring-rabbitmq-starter</artifactId>
		</dependency>
		<!-- Serializzazione JSON -->
		<dependency>
			<groupId>org.apache.camel.springboot</groupId>
			<artifactId>camel-jackson-starter</artifactId>
		</dependency>
		<!-- ... gestione di Date/Time JSR310 (LocalDate etc)-->
		<dependency>
			<groupId>com.fasterxml.jackson.datatype</groupId>
			<artifactId>jackson-datatype-jsr310</artifactId>
		</dependency>
		<!-- Fine RabbitMQ & Camel -->
		<!-- DB per prove -->
		<dependency>
			<groupId>com.h2database</groupId>
			<artifactId>h2</artifactId>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>org.flywaydb</groupId>
			<artifactId>flyway-core</artifactId>
		</dependency>
		<dependency>
			<groupId>org.flywaydb</groupId>
			<artifactId>flyway-database-hsqldb</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>

	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<executions>
					<execution>
						<goals>
							<goal>repackage</goal>
						</goals>
					</execution>
				</executions>
				<configuration>
					<mainClass>org.gds.poc.orch.manager.Application</mainClass>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.eclipse.jkube</groupId>
				<artifactId>kubernetes-maven-plugin</artifactId>
				<version>1.17.0</version>
				<configuration>
					<resources>
						<labels>
							<all>
								<property>
									<name>type</name>
									<value>ms</value>
								</property>
								<property>
									<name>dominio</name>
									<value>orchestration</value>
								</property>
							</all>
						</labels>
						<namespace>jentetest</namespace>
					</resources>
				</configuration>
			</plugin>
		</plugins>
	</build>
	<profiles>
		<profile>
			<id>k8s</id>
			<dependencies>
				<dependency>
					<groupId>org.springframework.boot</groupId>
					<artifactId>spring-boot-starter-actuator</artifactId>
				</dependency>
				<!-- Export metriche su OTLP -->
				<dependency>
					<groupId>io.micrometer</groupId>
					<artifactId>micrometer-registry-otlp</artifactId>
					<scope>runtime</scope>
				</dependency>
				<!-- Tracing -->
				<dependency>
					<groupId>io.opentelemetry</groupId>
					<artifactId>opentelemetry-exporter-otlp</artifactId>
				</dependency>
				<dependency>
					<groupId>io.micrometer</groupId>
					<artifactId>micrometer-tracing-bridge-otel</artifactId>
				</dependency>
				<!-- logging -->
				<dependency>
					<groupId>com.github.loki4j</groupId>
					<artifactId>loki-logback-appender</artifactId>
					<version>1.5.2</version>
				</dependency>
				<!-- Camel Observability-->
				<dependency>
					<groupId>org.apache.camel.springboot</groupId>
					<artifactId>camel-observation-starter</artifactId>
				</dependency>
			</dependencies>
		</profile>
	</profiles>

</project>
