apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: lra-coordinator
    csbexample: saga
  name: lra-coordinator
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 200Mi
