apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel-collector
  template:
    metadata:
      labels:
        app: otel-collector
    spec:
      containers:
      - name: otel-collector
        image: otel/opentelemetry-collector-contrib:0.82.0
        args:
          - --config=/conf-otel-collector/otel-collector.yaml
        volumeMounts:
        - name: config-volume-otel
          mountPath: /conf-otel-collector
        ports:
        - containerPort: 1888
        - containerPort: 8888
        - containerPort: 8889
        - containerPort: 13133
        - containerPort: 4317
        - containerPort: 4318
        - containerPort: 55679
      volumes:
      - name: config-volume-otel
        configMap:
          name:  otel-collector-config