apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tempo
  template:
    metadata:
      labels:
        app: tempo
    spec:
      containers:
      - name: tempo
        image: grafana/tempo:latest
        args:
          - --config.file=/conf-tempo/tempo.yaml
        volumeMounts:
        - name: config-volume-tempo
          mountPath: /conf-tempo
        ports:
        - containerPort: 3200
        - containerPort: 4317
      volumes:
      - name: config-volume-tempo
        configMap:
          name:  tempo-config
