server:
  port: 8080
client:
  protocollo:
    endpoint: http://localhost:8280
  verbale:
    endpoint: http://localhost:8180
camel:
  springboot:
    tracing: false
management:
  server:
    port: 9080
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always