spring:
  application:
    name: ssm-orchestator
server:
  port: 8080
client:
  protocollo:
    endpoint: http://localhost:8280
  verbale:
    endpoint: http://localhost:8180
management:
  server:
    port: 9080
  endpoints:
    web:
      exposure:
        include: "*"
  otlp:
    metrics:
      export:
        url: http://otel-collector:4318/v1/metrics
        step: 10s
    tracing:
      endpoint: http://otel-collector:4318/v1/traces
      export:
        step: 10s # Export interval set to 10 seconds
  tracing:
    sampling:
      probability: 1.0
  endpoint:
    health:
      show-details: always